# file: action.yml
# version: 1.0.0
# guid: 8a7f3c5e-9d2b-4e1a-b8c6-7f4d2e9a1b3c

name: "Release Docker Image"
description: "Build and publish multi-platform Docker images to registries"
author: "jdfalk"

branding:
  icon: "package"
  color: "blue"

inputs:
  context:
    description: "Docker build context directory"
    required: false
    default: "."
  dockerfile:
    description: "Path to Dockerfile"
    required: false
    default: "Dockerfile"
  platforms:
    description: "Comma-separated list of platforms to build for"
    required: false
    default: "linux/amd64,linux/arm64"
  registry:
    description: "Docker registry (e.g., docker.io, ghcr.io)"
    required: false
    default: "docker.io"
  image-name:
    description: "Docker image name (without registry prefix)"
    required: true
  tag:
    description: "Docker image tag"
    required: false
    default: "latest"
  additional-tags:
    description: "Additional tags (comma-separated)"
    required: false
    default: ""
  push:
    description: "Whether to push the image"
    required: false
    default: "true"
  build-args:
    description: "Build arguments (key=value, one per line)"
    required: false
    default: ""
  cache-from:
    description: "Cache source (type=registry,ref=...)"
    required: false
    default: ""
  cache-to:
    description: "Cache destination (type=registry,ref=...)"
    required: false
    default: ""
  username:
    description: "Registry username"
    required: false
    default: ""
  password:
    description: "Registry password or token"
    required: false
    default: ""

outputs:
  digest:
    description: "Image digest"
    value: ${{ steps.build.outputs.digest }}
  metadata:
    description: "Build result metadata"
    value: ${{ steps.build.outputs.metadata }}
  tags:
    description: "Generated tags"
    value: ${{ steps.meta.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      shell: bash

    - name: Log in to registry
      if: inputs.username != '' && inputs.password != ''
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
      shell: bash

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image-name }}
        tags: |
          type=raw,value=${{ inputs.tag }}
          ${{ inputs.additional-tags }}
      shell: bash

    - name: Build and push
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build-args }}
        cache-from: ${{ inputs.cache-from }}
        cache-to: ${{ inputs.cache-to }}
      shell: bash

    - name: Output summary
      shell: bash
      run: |
        echo "## Docker Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Image:** ${{ inputs.registry }}/${{ inputs.image-name }}" >> $GITHUB_STEP_SUMMARY
        echo "**Tags:** ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
        echo "**Platforms:** ${{ inputs.platforms }}" >> $GITHUB_STEP_SUMMARY
        echo "**Digest:** ${{ steps.build.outputs.digest }}" >> $GITHUB_STEP_SUMMARY
